# Generated by Django 4.1.7 on 2023-02-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_products_options_alter_categorymenu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', related_query_name='category', to='menu.menu'),
        ),
    ]
