# Generated by Django 4.1.7 on 2023-02-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menuitem_delete_categorymenu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Page',
        ),
    ]
