# Generated by Django 4.1.7 on 2023-02-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_rename_products_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
